### ISSUE TITLE
Expectation of LKJ RV is the identity matrix

### ISSUE THREAD

**Issue by bgoodri** [ben18785/distribution-zoo#44]
The app says there is "No simple expression" for the expectation and variance of a correlation matrix that is distributed LKJ. The expectation is the identity matrix, which can be seen most easily from page 1997 of the LKJ paper, where they say in step 2.b.i to generate a partial correlation (on a C-vine) independently from a symmetric beta distribution on the (-1,1) interval --- which has an expectation of zero --- and then in step 2.b.ii they say to use the recursive formula in equation (2) to obtain the corresponding Pearson correlation. If you rearrange equation (2) to isolate $\rho_{ij; L}$, then its expectation is zero if all three partial correlations have an expectation of zero.

This paper
https://scholar.google.com/scholar?cluster=8769718558497577003&hl=en&as_sdt=0,33
has a proof in the appendix that the marginal distribution of a correlation is symmetric beta over (-1,1) with both shape parameters `eta - 1 + size / 2` from which the marginal variance could be calculated, but I don't know of anyone who has worked out what the covariances between the Pearson correlations are.

**Comment by ben18785** [comment]
@bgoodri thanks for noticing this. My silly mistake. I have changed the formulae and latex.

**Comment by bgoodri** [comment]
Thank you. The app is still not quite right though. The marginal beta distribution is over the (-1,1) interval rather than the conventional (0,1) interval. Thus, you can multiply a conventional beta random variable by 2 and shift it by -1 to obtain a beta random variable over the (-1,1), which introduces a factor of 4 in the numerator of the variance calculation. Also, the marginal density has a slightly different [form](https://en.wikipedia.org/wiki/Beta_distribution#Four_parameters_2) with `c = 1` and `a = -1`.

**Comment by ben18785** [comment]
Thanks -- I should have twigged about the support given we're dealing with correlations! I (think) I've corrected this now. Thanks again.

**Comment by bgoodri** [comment]
Almost there. The 4 in the denominator of the marginal variance should be
in the numerator, since when you multiply a conventional Beta random
variable by 2 and shift it by -1 to put the random variable on the (-1,1)
interval, then the variance goes up by 2^2 .

**Comment by ben18785** [comment]
Wow, I've made a hash of this, sorry! Been a busy few days. Changed it
again. Let me know if anything is still wrong...
