### ISSUE TITLE
PDF for Student t doesn't change with sliders

### ISSUE THREAD

**Issue by fcooper8472** [ben18785/distribution-zoo#47]
Sliders don't seem to change the student t pdf

**Comment by fcooper8472** [comment]
ah, it might just be the server being really slow...

Definitely doesn't seem to change with df though?

**Comment by ben18785** [comment]
I just looked — think it’s the scale on the x axis that makes this hard to see.  Will change this so that it’s more obvious! Thanks for pointing this out.

**Comment by ben18785** [comment]
@fcooper8472 I just had a look and, to me at least, the sliders do seem to work ok and the change to the pdf, although, subtle does occur. So reckon I may keep as it is for now...
