### ISSUE TITLE
Inconsistency between Student Guide and Distribution Zoo

### ISSUE THREAD

**Issue by GeoffRussell** [ben18785/distribution-zoo#55]
Figure 8.27 shows 3 Gamma distributions ... (1,10) ... (4,2.5) ... and (10,1)   
The zoo makes plotting of 2 of these impossible, because of limits on the sliders.  
When I plot these distributions with R (using my own code for gamma because the built-in R code has different
parameterisation), the graph is rather different. 

![lambert-8 27](https://user-images.githubusercontent.com/6374333/103717396-51181480-5015-11eb-81e5-ff0d802b9717.png)

Here's my gamma function R code ... 

makegamma<-function(a,b) {
    g<-function(x) {
      (b^a)/gamma(a) * x^(a-1) * exp(-b*x)
    }
}

**Comment by fcooper8472** [comment]
@ben18785 I've just come across this: any thoughts?

**Comment by ben18785** [comment]
I completely missed this, sorry. @GeoffRussell this just because the distribution zoo matches the R parameterisation. Hence why the results differ from your own code.
